import { reactive } from 'vue';

export const store = reactive({
    cart_list: [
        {
            "name": "BoolCheeseBurger",
            "description": "You will never experience something this good, CHEESE!",
            "price": 7.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/cheeseburger--hero-mob.jpg.webp?itok=zUC2Hd7n",
            "availability": true,
            "ingredient_list": ["Bread", "Steak", "Cheese", "Onion", "Pickle", "Ketchup", "Senape"],
            "category": "Burger",
            "quantity": 1,
        },
        {
            "name": "BoolDoubleBurger",
            "description": "Double Meat Double Fun.",
            "price": 9.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/double-cheeseburger--hero-mob.jpg.webp?itok=h2Sb6fQv",
            "availability": true,
            "ingredient_list": ["Bread", "Steak", "Cheese", "Onion", "Pickle", "Ketchup", "Senape"],
            "category": "Burger",
            "quantity": 2,
        },
        {
            "name": "BoolChickenBurger",
            "description": "Sometimes you could admit that CHICKEN is better than Steak.",
            "price": 6.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/chickenburger--hero-mob.jpg.webp?itok=3ii-KClB",
            "availability": false,
            "ingredient_list": ["Bread", "Chicken", "Mayonnaise"],
            "category": "Burger",
            "quantity": 3,
        },
        {
            "name": "BoolFishBurger",
            "description": "Aaaaargh, Fish o'Neal.",
            "price": 4.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/filet-o-fish--hero-mob.jpg.webp?itok=kxKSQ52V",
            "availability": true,
            "ingredient_list": ["Bread", "Cod", "Mayonnaise"],
            "category": "Burger",
            "quantity": 1,
        },
        {
            "name": "BoolBaconBurger",
            "description": "Just BACON, What Else? ",
            "price": 9.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/gran-crispy-mcbacon--hero-mob_0.jpg.webp?itok=IxGQroUp",
            "availability": true,
            "ingredient_list": ["Bread", "Steak", "Cheese", "Onion", "Bacon", "Ketchup", "Senape"],
            "category": "Burger",
            "quantity": 1,
        },
        {
            "name": "BoolSelectionBurger",
            "description": "Hey, if Gordon says it's good, it has to be good.",
            "price": 10.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/myselection-chicken-avocado--hero-mob.jpg?itok=6B4inxSd",
            "availability": false,
            "ingredient_list": ["Bread", "Chicken", "Avocado", "Bacon", "Radish", "Tomato", "Cheese"],
            "category": "Burger",
            "quantity": 4,
        },
        {
            "name": "BoolFries",
            "description": "Do I have to add anything?",
            "price": 3.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/patate-regolari_mobile_0.jpg.webp?itok=dHGCytPo",
            "availability": true,
            "ingredient_list": ["Potato"],
            "category": "Sides",
            "quantity": 1,
        },
        {
            "name": "BoolNuggets",
            "description": "MUST-HAVE!",
            "price": 2.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/chicken-mcnuggets_mobile.jpg.webp?itok=-3FSOlc1",
            "availability": true,
            "ingredient_list": ["Chicken", "Bread"],
            "category": "Sides",
            "quantity": 1,
        },
        {
            "name": "Water",
            "description": "Lilia Water Plastic Bottle",
            "price": 0.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/acqua-lilla_mobile.jpg.webp?itok=rSdWmsOF",
            "availability": true,
            "ingredient_list": ["water"],
            "category": "Drink",
            "quantity": 2,
        },
        {
            "name": "BoolCoke",
            "description": "DRINK, DRINK DRINK!",
            "price": 3.99,
            "photo": "https://www.mcdonalds.it/sites/default/files/styles/compressed/public/products/cup-bibite-mobile_0.jpg.webp?itok=zUg1ivDC",
            "availability": true,
            "ingredient_list": ["water", "sugar"],
            "category": "Drink",
            "quantity": 20,
        }
    ]
});
